Repository vshn/cloudscale-metrics-collector, pull requests merged in 2022-11, with the labels that each got.

#22 extract information from k8s API
  .gitignore
  README.md
  accumulate.go
  accumulate_test.go
  go.mod
  go.sum
  main.go
  pkg/kubernetes/kubernetes.go
Labels: enhancement

#27 Remove `jsonnetfile.*`
  component/jsonnetfile.json
  component/jsonnetfile.lock.json
Labels: dependency

#23 fix deployment for cloudscale-metrics-collector
  component/Makefile.vars.mk
  component/class/cloudscale-metrics-collector.yml
  component/class/defaults.yml
  component/component/app.jsonnet
  component/component/main.jsonnet
  component/tests/cloudscale-metrics-collector.yml
  component/tests/collector-exoscale-ch-gva-2-0.yml
  component/tests/golden/cloudscale-metrics-collector/cloudscale-metrics-collector/apps/cloudscale-metrics-collector.yaml
  component/tests/golden/cloudscale-metrics-collector/cloudscale-metrics-collector/cloudscale-metrics-collector/cronjob.yaml
  component/tests/golden/cloudscale-metrics-collector/cloudscale-metrics-collector/cloudscale-metrics-collector/secrets.yaml
  component/tests/golden/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/apps/collector-exoscale-ch-gva-2-0.yaml
  component/tests/golden/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/cronjob.yaml
  component/tests/golden/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/secrets.yaml
  component/tests/golden/defaults/cloudscale-metrics-collector/cloudscale-metrics-collector/secrets.yaml
  docs/modules/ROOT/pages/how-tos/installation.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#28 upgrade to v0.5.1
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector/cloudscale-metrics-collector/cloudscale-metrics-collector/cronjob.yaml
  component/tests/golden/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/collector-exoscale-ch-gva-2-0/cronjob.yaml
Labels: change
